# Generated by Django 2.1.7 on 2019-02-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsecond',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Human', verbose_name='评论的作者'),
        ),
        migrations.AddField(
            model_name='commentsecond',
            name='first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.CommentFirst', verbose_name='一级评论'),
        ),
        migrations.AddField(
            model_name='commentsecond',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.CommentSecond', verbose_name='回复的评论ID'),
        ),
        migrations.AddField(
            model_name='commentfirst',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Human', verbose_name='评论的作者'),
        ),
        migrations.AddField(
            model_name='commentfirst',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.Chapter', verbose_name='章节'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='所属电子书'),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Human'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='book.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='article',
            name='chapter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.Chapter', verbose_name='所属章节'),
        ),
    ]
