# Generated by Django 2.1.7 on 2019-02-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='avatar',
            field=models.CharField(default='', max_length=100, verbose_name='用户头像'),
        ),
    ]
